services:
    db:
        image: mysql:8.0
        platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
        container_name: youl-log-db
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - '${DB_PORT}:3306'
        volumes:
            - db_data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'

volumes:
    db_data:
